version: "3.3"

services: 
    database: 
        image: postgres
        container_name: db_ticket
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=ticketwindow
            - POSTGRES_PASSWORD=ticketwindow
            - POSTGRES_DB=ticketwindow
        volumes:
            - pgdata:/data/postgres
volumes: 
    pgdata:   
        driver: local